#!/bin/bash
# setup-hooks.sh
# Installs post-commit hooks into each submodule so that committing inside
# frontend-pulse or backend-pulse automatically stages the updated submodule
# pointer in the parent (pulse) repo.
#
# Run this once after cloning pulse (or after re-initializing submodules):
#   bash scripts/setup-hooks.sh

set -e

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

install_hook() {
  local SUBMODULE="$1"
  local HOOKS_DIR="${REPO_ROOT}/.git/modules/${SUBMODULE}/hooks"

  if [ ! -d "$HOOKS_DIR" ]; then
    echo "⚠️  Hooks dir not found for ${SUBMODULE}: ${HOOKS_DIR}"
    echo "   Make sure the submodule is initialized: git submodule update --init"
    return 1
  fi

  cat > "${HOOKS_DIR}/post-commit" << HOOK
#!/bin/bash
# Auto-generated by scripts/setup-hooks.sh
# Stages the updated ${SUBMODULE} pointer in the parent (pulse) repo after each commit.

SUBMODULE_GIT_DIR="\$(git rev-parse --absolute-git-dir 2>/dev/null)"
PARENT_ROOT="\$(cd "\${SUBMODULE_GIT_DIR}/../../.." && pwd)"

if [ ! -f "\${PARENT_ROOT}/.gitmodules" ]; then
  exit 0
fi

NEW_HASH="\$(git rev-parse HEAD)"
cd "\${PARENT_ROOT}" || exit 0
git add ${SUBMODULE}

echo ""
echo "✓ [${SUBMODULE} post-commit] Staged updated pointer → \${NEW_HASH:0:7}"
echo "  Now run:  git commit -m \"chore: update ${SUBMODULE}\"  inside pulse"
HOOK

  chmod +x "${HOOKS_DIR}/post-commit"
  echo "✓ Hook installed for ${SUBMODULE}"
}

echo "Installing submodule post-commit hooks..."
install_hook "frontend-pulse"
install_hook "backend-pulse"
echo ""
echo "Done! From now on, committing inside frontend-pulse or backend-pulse"
echo "will automatically stage the pointer update in the pulse repo."
echo "You only need to run: git commit -m '...' from the pulse root."
